name: Bienvenida a nuevos Issues
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  comentar_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comentar en el issue abierto
        uses: peter-evans/create-or-update-comment@v3
        if: github.event_name == 'issues'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ¡Hola @${{ github.actor }}! 👋
            Gracias por abrir este Issue en mi proyecto. Lo revisaré lo antes posible.
      
      - name: Mensaje de ejecución manual
        if: github.event_name == 'workflow_dispatch'
        run: echo "El flujo se ha ejecutado manualmente, esperando a que se abra un Issue real."
